name: Run unit tests on java scripts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/*.yaml"
      - "**/*.conf"
      - "**/*.stoverride"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run user script
        run: node ./resource/resource-parser.js
